name: irhydra
dependencies:
  archive: any
  browser: any
  collection: any
  fixnum: any
  js: 0.2.2
  paper_elements: any
  polymer: '>=0.12.0-dev'
  sass: 0.3.1
transformers:
- sass
- polymer:
    entry_points: web/index.html
